#!/usr/bin/env python3
"""
generate-readiness-scorecard.py — Populate the CADRE readiness scorecard.

Usage:
    # Score from CLI args (7 dims, each 0-4)
    python3 generate-readiness-scorecard.py \\
        --client "NorthlineCo" \\
        --engagement NL-2026-0341 \\
        --scores 3 2 2 1 2 2 2 \\
        --out scorecard.md

    # Score from a JSON file
    python3 generate-readiness-scorecard.py \\
        --input readiness-scores.json \\
        --out scorecard.md

The scorecard skeleton mirrors readiness/scoring-template.md. The output
is plain markdown ready for branded docx conversion via the bhil-docx skill.

JSON input schema:
    {
      "client": "NorthlineCo",
      "engagement_id": "NL-2026-0341",
      "diagnostic_date": "2026-04-22",
      "lead_consultant": "Barry Hurd",
      "scores": {
        "data_readiness": 3,
        "tooling_readiness": 2,
        "process_readiness": 2,
        "evaluation_maturity": 1,
        "operational_readiness": 2,
        "governance_readiness": 2,
        "team_readiness": 2
      },
      "evidence": {
        "data_readiness": "ERP exports clean; CRM has nulls in 18% of rows.",
        ...
      }
    }

Composite tiers:
    24-28: Ready          — proceed to Full or Complete SKU
    17-23: Mostly Ready    — Full SKU with targeted remediation sprint
    10-16: Approaching     — Express SKU; remediation before Full
     0-9 : Not Ready       — Express + foundational engagement, no Full yet

Exit codes:
    0  scorecard generated
    1  invalid input (missing dims, out-of-range scores, etc.)
    2  I/O error
"""

import argparse
import json
import sys
from datetime import date
from pathlib import Path

DIMENSIONS = [
    ("data_readiness", "Data Readiness"),
    ("tooling_readiness", "Tooling Readiness"),
    ("process_readiness", "Process Readiness"),
    ("evaluation_maturity", "Evaluation Maturity"),
    ("operational_readiness", "Operational Readiness"),
    ("governance_readiness", "Governance Readiness"),
    ("team_readiness", "Team Readiness"),
]

TIER_LABELS = [
    (24, "Ready", "Proceed to Full or Complete SKU."),
    (17, "Mostly Ready", "Full SKU with a targeted remediation sprint."),
    (10, "Approaching Ready", "Express SKU first; remediation before Full."),
    (0, "Not Ready", "Express + foundational engagement before any Full."),
]


def tier_for(composite: int) -> tuple[str, str]:
    for floor, label, recommendation in TIER_LABELS:
        if composite >= floor:
            return label, recommendation
    return "Not Ready", "Express + foundational engagement before any Full."


def render(payload: dict) -> str:
    scores = payload["scores"]
    evidence = payload.get("evidence", {})
    composite = sum(scores[k] for k, _ in DIMENSIONS)
    tier, recommendation = tier_for(composite)

    lines = [
        f"# Readiness Diagnostic Scorecard — {payload['client']}",
        "",
        f"- **Engagement ID**: {payload['engagement_id']}",
        f"- **Diagnostic Date**: {payload.get('diagnostic_date', date.today().isoformat())}",
        f"- **Lead Consultant**: {payload.get('lead_consultant', 'Barry Hurd')}",
        f"- **Composite Score**: **{composite} / 28** — *{tier}*",
        "",
        "## Recommendation",
        "",
        recommendation,
        "",
        "## Dimension Scores",
        "",
        "| Dimension | Score | Evidence |",
        "|---|---|---|",
    ]
    for key, label in DIMENSIONS:
        score = scores[key]
        ev = evidence.get(key, "_(evidence pending)_").replace("|", "\\|")
        lines.append(f"| {label} | {score}/4 | {ev} |")

    lines += [
        "",
        "## Score Bands (per dimension)",
        "",
        "- **4** — Production-grade. No remediation needed.",
        "- **3** — Strong, minor gaps. Proceed with light coaching.",
        "- **2** — Workable, material gaps. Plan a remediation sprint.",
        "- **1** — Significant gaps. Remediation precedes Full SKU.",
        "- **0** — Absent or blocking. Foundational engagement required.",
        "",
        "## Composite Tiers",
        "",
        "| Range | Tier | Path |",
        "|---|---|---|",
        "| 24–28 | Ready | Full or Complete SKU |",
        "| 17–23 | Mostly Ready | Full SKU + targeted remediation |",
        "| 10–16 | Approaching Ready | Express SKU first |",
        "| 0–9 | Not Ready | Express + foundational engagement |",
        "",
        "## Notes",
        "",
        "This scorecard is the artifact handoff from the readiness diagnostic ",
        "(see `readiness/day-runbook.md`) to the engagement charter. It is one ",
        "of three required inputs for the Full SKU charter; the others are the ",
        "scope-of-work and the pricing addendum.",
        "",
        "---",
        "_Generated by `tools/scripts/generate-readiness-scorecard.py`_",
        "",
    ]
    return "\n".join(lines)


def load_payload(args) -> dict:
    if args.input:
        with open(args.input, "r", encoding="utf-8") as f:
            payload = json.load(f)
    else:
        if not (args.client and args.engagement and args.scores):
            raise ValueError("--client, --engagement, and --scores are required when --input is not given.")
        if len(args.scores) != 7:
            raise ValueError(f"--scores expects 7 integers, got {len(args.scores)}.")
        payload = {
            "client": args.client,
            "engagement_id": args.engagement,
            "diagnostic_date": date.today().isoformat(),
            "lead_consultant": "Barry Hurd",
            "scores": {key: args.scores[i] for i, (key, _) in enumerate(DIMENSIONS)},
            "evidence": {},
        }

    # Validate
    scores = payload.get("scores", {})
    for key, label in DIMENSIONS:
        if key not in scores:
            raise ValueError(f"Missing dimension: {key} ({label})")
        if not isinstance(scores[key], int) or not (0 <= scores[key] <= 4):
            raise ValueError(f"Score for {key} must be int in [0, 4]; got {scores[key]}.")
    return payload


def main() -> int:
    p = argparse.ArgumentParser(description="Generate a CADRE readiness scorecard.")
    p.add_argument("--client", help="Client display name.")
    p.add_argument("--engagement", help="Engagement ID, e.g. NL-2026-0341.")
    p.add_argument("--scores", nargs=7, type=int, metavar="N",
                   help="Seven integers (0-4), one per dimension, in canonical order.")
    p.add_argument("--input", type=Path, help="Path to JSON payload (overrides CLI scoring args).")
    p.add_argument("--out", type=Path, default=Path("scorecard.md"), help="Output markdown path.")
    args = p.parse_args()

    try:
        payload = load_payload(args)
    except (ValueError, json.JSONDecodeError, FileNotFoundError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    md = render(payload)

    try:
        args.out.write_text(md, encoding="utf-8")
    except OSError as e:
        print(f"I/O error writing {args.out}: {e}", file=sys.stderr)
        return 2

    composite = sum(payload["scores"][k] for k, _ in DIMENSIONS)
    tier, _ = tier_for(composite)
    print(f"Wrote {args.out} — composite {composite}/28 ({tier}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
